-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPxgYK+de8xrcNEFX
LC2UTVXR3vFSl9p3jaCZvQ0QvmSgCgYIKoZIzj0DAQehRANCAARxxlefZNc5+Pij
D7obCRmCYpYyX1uudJ1djljd6iVwn4wt3AzSnnHUBayHZA0BjxLV3aU/ZZlYkbGE
crtkYzxw
-----END PRIVATE KEY-----